name: crawl

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore: ['README.md']
  schedule:
  - cron: '0 * * * *' # Hourly

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ./crawl.sh
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "update: $(date -u)" || exit 0
        git push

